import type { GenomeLocus } from './catalog';
import type { Expression } from './registry';

/**
 * Short human descriptions of each koi locus for the genome view's hover notes. Text only: nothing here is read by
 * expression, inheritance or saves, so wording can change freely without touching any fish.
 */
export const KOI_LOCUS_NOTES: Record<GenomeLocus, string> = {
  body_length: 'Stretches the body relative to its depth and adds a little to adult size.',
  body_depth: 'How tall the body is from back to belly. Deeper bodies swim a little slower.',
  body_taper: 'How sharply the body narrows toward the tail.',
  spine_curve: 'A slight resting bend of the spine, up or down, around a straight midpoint.',
  head_length: 'Head length along the body. Scaled further by the head gain locus.',
  snout_length: 'How far the snout reaches in front of the eyes.',
  eye_size: 'Eye diameter relative to the head.',
  eye_position: 'Where the eye sits, from low on the head to high.',
  iris_hue: 'Base iris color, from warm amber through green to blue.',
  pupil_size: 'Pupil size within the iris.',
  mouth_size: 'Mouth width at the tip of the snout.',
  barbel_length: 'Length of the whisker-like barbels beside the mouth.',
  tail_length: 'Caudal fin length. Scaled by fin gain; long tails add drag and oxygen need.',
  tail_spread: 'How wide the tail fans open.',
  tail_fork: 'Depth of the notch between the upper and lower tail lobes.',
  dorsal_height: 'Height of the fin along the back. Scaled by fin gain.',
  pectoral_length: 'Length of the paired side fins behind the head. Scaled by fin gain.',
  fin_pigment: 'How much body color carries into the fins.',
  red: 'Red pigment strength. Scaled by pigment gain.',
  yellow: 'Yellow pigment strength.',
  black: 'Black pigment strength. Scaled by pigment gain; removed entirely when the melanin switch is A5/A5.',
  white: 'White ground color between patches.',
  reflectivity: 'Glossy sheen of the scales. The metallic switch can override it.',
  translucency: 'How see-through the skin and fins look.',
  pattern_frequency: 'How many patches the pattern places along the body.',
  pattern_scale: 'Size of each pattern patch.',
  pattern_warp: 'How irregular and wavy patch outlines are.',
  pattern_symmetry: 'How closely the two flanks mirror each other.',
  pattern_edge: 'Crisp versus soft patch borders.',
  speckle: 'Fine dark speckling over the body.',
  size_1: 'Major adult size locus: the largest single share of adult length potential.',
  growth_rate: 'How fast the fish approaches its adult size.',
  longevity: 'Lifespan potential, about 8 to 32 game years.',
  metabolism: 'Food and oxygen use. Higher metabolism eats more of the tank food pool.',
  oxygen_demand: 'Oxygen need per size. Heavy demand strains poorly aerated tanks.',
  fertility: 'Courtship readiness and how quickly a pair completes courtship.',
  thrust: 'Swimming power. Cruising speed also falls with long tails and deep bodies.',
  turning: 'How tightly the fish turns.',
  activity: 'How much time the fish spends moving rather than resting.',
  sociability: 'Tendency to school with tankmates.',
  boldness: 'Willingness to explore open water and approach food first.',
  curiosity: 'Interest in decorations, new objects and nearby fish.',
  size_2: 'Second adult size locus, adding to size 1.',
  pigment_gain: 'Global multiplier on red and black pigment strength.',
  fin_gain: 'Global multiplier on tail, dorsal and pectoral fin size.',
  head_gain: 'Scales how strongly head length is expressed.',
  melanin_switch: 'Recessive switch: two A5 copies remove all black pigment.',
  metallic_switch: 'Recessive switch: two A5 copies give strong metallic color.',
  base_color: 'Main body color. Classic dominates; a variant shows only with two nonclassic copies.',
  accent_color: 'Color of the patches over the base. Classic dominates.',
  dot_color: 'Color of spots and speckles. Rainbow dominates; two other colors both show.',
  iris_color: 'Named eye color. Classic dominates.',
  shimmer: 'Additive iridescent shimmer; faint levels are not drawn.',
  scale_type: 'Scale type. Smooth scales dominate, so variant scales need two copies.',
  body_motif: 'Motif drawn over the body. One copy shows faintly; two different motifs mix.',
  motif_density: 'How many motif elements are drawn.',
  motif_scale: 'Size of each motif element.',
  motif_contrast: 'How strongly motifs stand out from the body color.',
  motif_reach: 'How far body motifs extend toward the fins.',
  fin_motif: 'Motif drawn on the fins. One copy shows faintly.',
  tail_topology: 'Tail structure. A paired fan or crown tail needs two variant copies.',
  lobe_balance: 'Relative size of the upper and lower tail lobes.',
  topology_spread: 'How far a paired or crown tail splays apart.',
  dorsal_form: 'Dorsal fin form. A reduced or missing dorsal needs two variant copies.',
  barbel_count: 'Number of barbels: two by default; none, four or six need variant copies on both homologs.',
  fin_ray_density: 'How many rays stiffen the fins.',
};

export const KOI_EXPRESSION_NOTES: Record<Expression, string> = {
  additive: 'Additive: both copies add up; A0 is lowest and A5 highest.',
  'recessive-switch': 'Recessive switch: only two A5 copies change the fish; one copy is carried silently.',
  'classic-dominant': 'Classic-dominant: one classic copy hides a variant.',
  'rainbow-dominant': 'Rainbow dominates; two different other colors are both shown.',
  recessive: 'Recessive: the variant shows only with two copies.',
  overlay: 'Overlay: each copy draws its own motif; one copy is faint.',
  'structural-recessive': 'Structural recessive: two variant copies are needed to change the form.',
  'barbel-series': 'Recessive series: one standard copy keeps two barbels.',
};
